# adapt options
model_type: EDA_RC
gradclip: 5
batchsize: 32
max_epochs: 100
num_frames: 500
chunk_size: 50
optimizer: adam
loss_factor: 1/1/1/1/0.1
lr: 1e-5
gradient_accumulation_steps: 1
seed: 777
gpu: 1
